version: "3.9"

services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "2306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - mysql
    healthcheck:
      test:
        - CMD
        - ping
        - "-p${password}"
      retries: 3
      timeout: 5s
networks:
  mysql:
    driver: bridge
volumes:
  mysql:
    driver: local
