//пример инфы для создания пейджей
export const data = {
    products: [
        {
            id: 0,
            category: 'Шпатлевка',
            name: 'Шпатлевка BCRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'BCRYL-PUTZ',
            description: 'Описание продукта 1',
            price: 9.66,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 1,
            category: 'Апатлевка',
            name: 'Апатлевка BCRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'BCRYL-PUTZ',
            description: 'Описание продукта 2',
            price: 0,
            currency: '',
            image: "/images/1.png",
            quantity: 0,
        },
        {
            id: 2,
            category: 'Шпатлевка',
            name: 'Шпатлевка ACRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'ACRYL-PUTZ',
            description: 'Описание продукта 3',
            price: 200,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 3,
            category: 'Шпатлевка',
            name: 'Шпатлевка ACRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'ACRYL-PUTZ',
            description: 'Описание продукта 4',
            price: 400,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 4,
            category: 'Бпатлевка',
            name: 'Бпатлевка ACRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'ACRYL-PUTZ',
            description: 'Описание продукта 5',
            price: 500,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 5,
            category: 'Бпатлевка',
            name: 'Бпатлевка ACRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'ACRYL-PUTZ',
            description: 'Описание продукта 6',
            price: 600,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 6,
            category: 'Бпатлевка',
            name: 'Бпатлевка BCRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'BCRYL-PUTZ',
            description: 'Описание продукта 7',
            price: 700,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
        {
            id: 7,
            category: 'Апатлевка',
            name: 'Апатлевка ACRYL-PUTZ ST10. Старт-финиш. 20 кг. Польша.',
            brand: 'ACRYL-PUTZ',
            description: 'Описание продукта 7',
            price: 700,
            currency: 'BYN',
            image: "/images/1.png",
            quantity: 100,
        },
    ],
};